dist: bionic
language: go

branches:
  only:
    - master

env:
  global:
    - GO111MODULE=on
    - GOLANGCI_LINT_VERSION=1.19.1

cache:
  directories:
    - ${HOME}/.cache/go-build
    - ${GOPATH}/pkg/mod
  npm: true
  yarn: true

_lint_job: &lint_job
  env: CACHE_NAME=lint
  before_install:
    - if [ -f .github/.ci.conf ]; then . .github/.ci.conf; fi
  install: skip
  before_script:
    - |
      curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh \
        | bash -s - -b $GOPATH/bin v${GOLANGCI_LINT_VERSION}
  script:
    - bash .github/lint-commit-message.sh
    - bash .github/lint-filename.sh
    - golangci-lint run ./...

_build_job: &build_job
  env: CACHE_NAME=build
  script:
    - go build ./cmd/biz
    - go build ./cmd/islb
    - go build ./cmd/sfu

_test_job: &test_job
  env: CACHE_NAME=test
  before_install:
    - if [ -f .github/.ci.conf ]; then . .github/.ci.conf; fi
    - go mod download
  install:
    - go build ./...
  before_script:
    - docker-compose -f docker-compose.test.yml up -d
  script:
    - testpkgs=${TEST_PACKAGES:-$(go list ./... | grep -v cmd | grep -v conf)}
    - coverpkgs=$(echo "${testpkgs}" | paste -s -d ',')
    - |
      go test \
        -coverpkg=${coverpkgs} -coverprofile=cover.out -covermode=atomic \
        ${TEST_EXTRA_ARGS:-} \
        -v -race ${testpkgs}
    - if [ -n "${TEST_HOOK}" ]; then ${TEST_HOOK}; fi
  after_success:
    - travis_retry bash <(curl -s https://codecov.io/bash) -c -F go
_test_i386_job: &test_i386_job
  env: CACHE_NAME=test386
  services: docker
  before_install:
    - if [ -f .github/.ci.conf ]; then . .github/.ci.conf; fi
  before_script:
    - docker-compose -f docker-compose.test.yml up -d
  script:
    - testpkgs=${TEST_PACKAGES:-$(go list ./... | grep -v cmd | grep -v conf)}
    - |
      docker run \
        -u $(id -u):$(id -g) \
        -e "GO111MODULE=on" \
        -e "CGO_ENABLED=0" \
        -v ${PWD}:/go/src/github.com/pion/$(basename ${PWD}) \
        -v ${HOME}/gopath/pkg/mod:/go/pkg/mod \
        -v ${HOME}/.cache/go-build:/.cache/go-build \
        -w /go/src/github.com/pion/$(basename ${PWD}) \
        --network ion_default \
        -it i386/golang:${GO_VERSION}-alpine \
        /usr/local/go/bin/go test \
          ${TEST_EXTRA_ARGS:-} \
          -v ${testpkgs}

jobs:
  include:
    - <<: *lint_job
      name: Lint 1.14
      go: 1.14
    - <<: *build_job
      name: Build 1.13
      go: 1.13
    - <<: *build_job
      name: Build 1.14
      go: 1.14
    - <<: *test_job
      name: Test 1.13
      go: 1.13
    - <<: *test_job
      name: Test 1.14
      go: 1.14
    # - <<: *test_i386_job
    #   name: Test i386 1.13
    #   env: GO_VERSION=1.13
    #   go: 1.14 # version for host environment used to go list
    # - <<: *test_i386_job
    #   name: Test i386 1.14
    #   env: GO_VERSION=1.14
    #   go: 1.14 # version for host environment used to go list

notifications:
  email: false
