version: '3.7'

services:
  # web:
    # build:
    #   dockerfile: ./docker/web.Dockerfile
    #   context: .
    # image: pionwebrtc/ion-web
    # volumes:
    #   - "./docker/Caddyfile:/etc/Caddyfile"
    # ports:
    #   - 80:80
    #   - 8080:8080
    #   - 8443:8443
    # depends_on:
    #   - biz
    # environment:
    # - WWW_URL
    # - ADMIN_EMAIL

  sfu:
    build:
      dockerfile: ./docker/sfu.Dockerfile
      context: .
    command: "-c /configs/sfu.toml"
    restart: always
    # image: pionwebrtc/ion-sfu
    volumes:
      - "./docker/sfu.toml:/configs/sfu.toml"
    ports:
      - "5000-5200:5000-5200/udp"
    depends_on:
      - nats
      - etcd

  avp:
    build:
      dockerfile: ./docker/avp.Dockerfile
      context: .
    # command: "-c /configs/avp.toml"
    # image: ion_avp:0.0.2
    volumes:
      - "./:/go/src/github.com/pion/ion"
      - "./docker/avp.toml:/configs/avp.toml"
    depends_on:
      - nats
      - etcd

  biz:
    build:
      dockerfile: ./docker/biz.Dockerfile
      context: .
    # image: pionwebrtc/ion-biz
    command: "-c /configs/biz.toml"
    volumes:
      - "./docker/biz.toml:/configs/biz.toml"
    ports:
      - "8443:8443"
    depends_on:
      - nats
      - etcd

  islb:
    build:
      dockerfile: ./docker/islb.Dockerfile
      context: .
    # image: pionwebrtc/ion-islb
    command: "-c /configs/islb.toml"
    volumes:
      - "./docker/islb.toml:/configs/islb.toml"
    depends_on:
      - nats
      - etcd
      - redis

  nats:
    image: nats

  etcd:
    image: gcr.io/etcd-development/etcd:v3.3.18
    entrypoint: "/usr/local/bin/etcd"
    command: "--listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379"

  redis:
    image: redis:5.0.7