version: '3.7'

services:
  # web conference demo
  web:
    build:
      dockerfile: web.Dockerfile
      context: .
    volumes:
      - "./configs:/cert"
      - "./docker/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 8080:443
    depends_on:
      - biz

  sfu:
    build:
      dockerfile: ./docker/sfu.Dockerfile
      context: .
    command: "-c /configs/sfu.toml"
    volumes:
      - "./docker/sfu.toml:/configs/sfu.toml"
    ports:
      - 6666:6666 # rtp
    depends_on:
      - nats
      - etcd

  biz:
    build:
      dockerfile: ./docker/biz.Dockerfile
      context: docker
    command: "-c /configs/biz.toml"
    volumes:
      - "./docker/biz.toml:/configs/biz.toml"
      - "./configs/cert.pem:/configs/cert.pem"
      - "./configs/key.pem:/configs/key.pem"
    ports:
      - 8443:8443 # websocket
    depends_on:
      - nats
      - etcd

  islb:
    build:
      dockerfile: ./docker/islb.Dockerfile
      context: .
    command: "-c /configs/islb.toml"
    volumes:
      - "./docker/islb.toml:/configs/islb.toml"
    depends_on:
      - nats
      - etcd
      - redis

  nats:
    image: nats

  etcd:
    image: gcr.io/etcd-development/etcd:v3.3.18
    entrypoint: "/usr/local/bin/etcd"
    command: "--listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379"

  redis:
    image: redis:5.0.7
