version: '3.7'

services:
  nats:
    image: nats
    ports:
      - 4222:4222

  etcd:
    image: gcr.io/etcd-development/etcd:v3.4.9
    entrypoint: "/usr/local/bin/etcd"
    command: "--listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://0.0.0.0:2379"
    ports:
      - 2379:2379

  redis:
    image: redis:5.0.9
    ports:
      - 6379:6379