[global]
pprof = ":6062"

# data center id
dc = "dc1"

[webrtc]
ice = ["stun:stun.l.google.com:19302"]

[rtp]
# listen port
port = 6667

[log]
level = "info"
# level = "debug"

[etcd]
# ["ip:port", "ip:port"]
addrs = ["etcd:2379"]

[nats]
url = "nats://nats:4222"

[avp]
[avp.processors.recorder]
outpath = "./"
[avp.processors.recorder.audio]
sampling = 4000
channels = 2