[global]
pprof = ":6060"

# internet ip
addr = "127.0.0.1"

# data center id
dc = "dc1"

[log]
level = "info"
# level = "debug"

[etcd]
# ["ip:port", "ip:port"]
addrs = ["etcd:2379"]

[signal]
#listen ip port
host = "0.0.0.0"
port = "8443"

[nats]
url = "nats://nats:4222"

