[global]
pprof = ":6061"
# data center id
dc = "dc1"

[log]
level = "info"

[etcd]
# ["ip:port", "ip:port"]
addrs = ["etcd:2379"]

[nats]
url = "nats://nats:4222"

[redis]
addrs = ["redis:6379"]
password = ""
db = 0
