[global]
pprof = ":6062"

# data center id
dc = "dc1"

# internet ip
addr = "127.0.0.1"

[receiver.video]
# the remb cycle sending to pub, this told the pub it's bandwidth
rembcycle = 2
# pli cycle sending to pub, and pub will send a key frame
plicycle = 1
# transport-cc cycle (experiment feature)
tcccycle = 1
# this limit the remb bandwidth
maxbandwidth = 1000
# max buffer time by ms
maxbuffertime = 1000

[webrtc]
# Range of ports that ion accepts WebRTC traffic on
# Format: [min, max]   and max - min >= 100
# portrange = [50000, 60000]
# if sfu behind nat, set iceserver
# [[webrtc.iceserver]]
# urls = ["stun:stun.stunprotocol.org:3478"]
# [[webrtc.iceserver]]
# urls = ["turn:turn.awsome.org:3478"]
# username = "awsome"
# credential = "awsome"

[log]
level = "debug"
stats = true

[etcd]
# ["ip:port", "ip:port"]
addrs = ["etcd:2379"]

[nats]
url = "nats://nats:4222"
