[global]
pprof = ":6062"

# data center id
dc = "dc1"

# internet ip
addr = "127.0.0.1"

[webrtc]
# if ion behind nat, uncomment one
# ice = ["stun:stun.l.google.com:19302"]
[webrtc.ice]
urls = ["stun:stun.stunprotocol.org:3478"]
username = ""
credential = ""

# Range of ports that ion accepts WebRTC traffic on
ephemeral-udp-port-range = []

[rtp]
# listen port
port = 6666

[log]
level = "info"
# level = "debug"

[etcd]
# ["ip:port", "ip:port"]
addrs = ["127.0.0.1:2379"]

[nats]
url = "nats://127.0.0.1:4222"

